name: crystal_grimoire_fresh
description: "🔮 Your mystical crystal identification and spiritual guidance companion with holographic UI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  cloud_functions: ^5.2.6
  firebase_analytics: ^11.5.0
  firebase_messaging: ^15.2.7
  firebase_performance: ^0.10.1+7
  
  # Auth
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^5.0.0
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  animations: ^2.0.11
  
  # Media & Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  video_player: ^2.8.1
  audioplayers: ^6.0.0
  
  # Storage & State
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  path_provider: ^2.1.1
  
  # Utilities
  http: ^1.1.0
  dio: ^5.4.0
  uuid: ^4.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.2
  permission_handler: ^11.4.0
  
  # Payments
  js: ^0.6.7  # For Stripe web integration
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
  # Icons & Assets
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/crystals/
    - assets/animations/
    - assets/icons/
    - assets/sounds/
    - assets/data/
  
  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: assets/fonts/Orbitron-Regular.ttf
  #       - asset: assets/fonts/Orbitron-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Orbitron-Black.ttf
  #         weight: 900